name: Test and contract verification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Typecheck
        run: yarn typecheck

      - name: Run tests and verify contracts
        run: yarn test
